steps:
  - id: "set-up-gcloud"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args: ["-c", "echo $$_CREDENTIALS > /credentials.json"]

  - id: "terraform-fmt-check"
    name: "hashicorp/terraform:$_TERRAFORM_CLIENT_VERSION"
    args: ["fmt", "-check", "-diff"]

  - id: "terraform-init"
    name: "hashicorp/terraform:$_TERRAFORM_CLIENT_VERSION"
    args: ["init"]

  - id: "terraform-plan"
    name: "hashicorp/terraform:$_TERRAFORM_CLIENT_VERSION"
    args: ["plan", "-lock-timeout=120s", "-var=project=${_PROJECT}", "-var=credentials=/credentials.json"]

timeout: "3600s"

availableSecrets:
  secretManager:
    - versionName: projects/$_PROJECT/secrets/$_SECRET_NAME/versions/latest
      env: '_CREDENTIALS'
